version: 2

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - vendor
    - third_party

linters:
  enable:
    - govet
    - staticcheck
    - errcheck

linters-settings:
  goimports:
    local-prefixes: github.com/iflytek/astron-xmod-shim

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0