# 示例配置文件 - astron-xmod-shim

# 副本数量
replicaCount: 1

# 容器镜像配置
image:
  repository: astron-xmod-shim
  pullPolicy: IfNotPresent
  tag: "1.16.0"

# 主机网络配置
useHostNetwork: true

# 服务配置
service:
  type: ClusterIP
  port: 8080

# 卷挂载配置
volumes:
  - name: config-volume
    hostPath:
      path: /path/to/your/astron-xmod-shim/conf
      type: Directory
  - name: maasmodels-volume
    hostPath:
      path: /mnt/maasmodels/
      type: Directory

# 容器内挂载点配置
volumeMounts:
  - name: config-volume
    mountPath: /app/conf
    readOnly: true
  - name: maasmodels-volume
    mountPath: /mnt/maasmodels/
    readOnly: true

# 资源限制配置（可选）
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# 节点选择器（可选）
# nodeSelector:
#   kubernetes.io/hostname: your-node-name

# 容忍度配置（可选）
# tolerations:
#   - key: "key"
#     operator: "Equal"
#     value: "value"
#     effect: "NoSchedule"